import type { AssetRef, ProjectDocument } from "../../lib/studio/types";
import {
  validateProject,
  type EditOperation,
} from "../../lib/studio/operations";
import { applyBoundSuggestions } from "../../lib/studio/retiming";
import {
  reframeFromSpeaker,
  type SpeakerRegion,
} from "../../src/studio/reframe";
export interface EditSuggestionInput {
  document: ProjectDocument;
  selectedItemIds: string[];
  kind: "silence" | "reframe";
  fit?: "contain" | "cover";
  /** Measured source silence from the local decoder, never generated by a model. */
  silence?: Record<string, { startUs: number; endUs: number }[]>;
  assets?: AssetRef[];
  speakerRegions?: Record<string, SpeakerRegion>;
}
export const applySuggestions = applyBoundSuggestions;
/** Deterministic local assistance costs nothing and never executes model code. */
export async function suggestEdits(
  input: EditSuggestionInput,
): Promise<EditOperation[]> {
  const { document: doc, selectedItemIds: ids } = input;
  validateProject(doc);
  if (
    !Array.isArray(ids) ||
    !ids.length ||
    ids.length > 50 ||
    new Set(ids).size !== ids.length ||
    !["silence", "reframe"].includes(input.kind)
  )
    throw Error("Choose selected items for assistance");
  const operations: EditOperation[] = [];
  let speaker = false;
  for (const id of ids) {
    const item = doc.items.find((i) => i.id === id);
    if (!item || item.linkedVideoId || item.detachedAudioId)
      throw Error("Selected item is missing or has detached audio");
    if (input.kind === "reframe") {
      const region = input.speakerRegions?.[id];
      if (region) {
        const asset = input.assets?.find((a) => a.id === item.assetId);
        if (!asset) throw Error("Speaker source unavailable");
        const crop = reframeFromSpeaker(
          region,
          asset.checksum,
          item.sourceInUs!,
          item.sourceOutUs!,
        );
        operations.push({
          type: "layer",
          itemId: id,
          changes: { crop, fit: "cover" },
        });
        speaker = true;
      } else {
        if (!["contain", "cover"].includes(input.fit ?? ""))
          throw Error("No speaker evidence: choose Fit or Fill");
        operations.push({
          type: "layer",
          itemId: id,
          changes: { fit: input.fit },
        });
      }
    } else {
      if (!item.assetId || item.freeze || item.loop || item.keyframes)
        throw Error("Silence assistance needs ordinary source footage");
      const silences = input.silence?.[id] ?? [];
      let start = item.sourceInUs!,
        end = item.sourceOutUs!;
      for (const interval of silences) {
        if (
          !Number.isFinite(interval.startUs) ||
          !Number.isFinite(interval.endUs) ||
          interval.endUs <= interval.startUs
        )
          throw Error("Invalid decoded silence evidence");
        if (interval.startUs <= start + 1000 && interval.endUs > start)
          start = Math.min(end, interval.endUs);
      }
      for (const interval of [...silences].reverse())
        if (interval.endUs >= end - 1000 && interval.startUs < end)
          end = Math.max(start, interval.startUs);
      const fps = doc.fps.numerator / doc.fps.denominator;
      const inFrame = Math.max(
          0,
          Math.ceil(((start - item.sourceInUs!) * fps) / (1e6 * item.speed)),
        ),
        outFrame = Math.min(
          item.durationFrames,
          Math.floor(((end - item.sourceInUs!) * fps) / (1e6 * item.speed)),
        );
      if (outFrame > inFrame && (inFrame > 0 || outFrame < item.durationFrames))
        operations.push({ type: "trim", itemId: id, inFrame, outFrame });
    }
  }
  if (!operations.length) return [];
  const proposal: EditOperation = {
    type: "suggested",
    baseRevision: doc.revision,
    baseDocument: JSON.stringify(doc),
    selectedItemIds: [...ids],
    operations,
    explanation:
      input.kind === "silence"
        ? "Trim measured leading/trailing silence from selected items; keep timeline positions. Interior pauses are preserved."
        : speaker
          ? "Crop to your confirmed speaker region. Automatic speaker recognition is unavailable."
          : "No speaker evidence: apply your chosen Fit or Fill.",
  };
  applyBoundSuggestions(doc, [proposal], ids);
  return [proposal];
}
